on:
  pull_request:
    types: [opened, synchronize]

jobs:
  tests:
    runs-on: android-runners
    timeout-minutes: 30
    name: Tests
    outputs:
      evaluation-data: ${{ steps.evaluator.outputs.result }}
    steps:
      - name: Fetch project repository
        uses: actions/checkout@v3

      - name: Fetch Blocked Files Checkout action
        uses: actions/checkout@v3
        with:
          repository: betrybe/blocked-files-checkout-action
          ref: v2
          path: .github/actions/blocked-files-checkout

      - name: Fetch JUnit Android Evaluator
        uses: actions/checkout@v3
        with:
          repository: betrybe/junit-android-evaluator-action
          ref: v2
          path: .github/actions/junit-android-evaluator-action

      - name: Run JUnit Android Evaluator
        id: evaluator
        uses: ./.github/actions/junit-android-evaluator-action
        with:
          pr_author_username: ${{ github.event.pull_request.user.login }}
          unit_test: false
          instrumented_test: true

  store-evaluation:
    runs-on: self-hosted
    needs: [tests]
    steps:
      - name: Fetch Store evaluation
        uses: actions/checkout@v3
        with:
          repository: betrybe/store-evaluation-action
          ref: v8.0
          path: .github/actions/store-evaluation
          token: ${{ secrets.GIT_HUB_PAT }}

      - name: Run Store evaluation
        uses: ./.github/actions/store-evaluation
        with:
          evaluation-data: ${{ needs.tests.outputs.evaluation-data }}
          environment: production
          token: ${{ secrets.GITHUB_TOKEN }}
